### ISSUE TITLE
Android leaveNamespace not implemented

### ISSUE THREAD

**Issue by jwhits** [triniwiz/nativescript-socketio#10]
In socketio.android.ts is there a reason why leaveNamespace is not implemented?

`leaveNamespace(): void {
        // Not Implemented
    }`

**Comment by db3coder** [comment]
It is because going through the code I haven't been able to come up with a way for it to leave the namespace without reconstructing a new socket object.

IOS however does provide functionality for this by the leaveNamespace method.

One thought that I had previously tried was using the same functionality as joinNamespace() but with the nsp as '/'. My previous efforts at this ended up with the previous namespace being rejoined.
